### ISSUE TITLE
Support intel arc graphics card

### ISSUE THREAD

**Issue by ytx222** [Kahsolt/stable-diffusion-webui-vae-tile-infer#2]
Does this project or multidiffusion-upscaler-for-automatic1111 have plans to support intel arc graphics card? I encountered an error in the process of using arc
=====
/home/ytx/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py
Traceback (most recent call last):
   File "/home/ytx/stable-diffusion-webui/modules/scripts.py", line 404, in postprocess
     script. postprocess(p, processed, *script_args)
   File "/home/ytx/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/scripts/vae_optimize.py", line 846, in postprocess
     devices.torch_gc()
AttributeError: module 'modules.devices' has no attribute 'torch_gc'

**Comment by Kahsolt** [comment]
This error seems to have nothing to do with platform-specified evils, but your sd-webui distro is toooo old or not the official one (?

This `modules.devices.torch_gc()` is an sd-webui inner API, it should be found at any commits after [#abb83239e5d708adf72fa457c3de81603e7281d3](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/abb83239e5d708adf72fa457c3de81603e7281d3), which is dated back to Aug 24, 2022 🤔

**Comment by ytx222** [comment]
Yes, for arc to work, I'm using this https://github.com/jbaboval/stable-diffusion-webui/tree/oneapi
He is much, much behind the latest version, but I can't help it, thank you for your reply

**Comment by Kahsolt** [comment]
😥 Then this is really unusual case...
I guess we're not going to add lines for this trivial compatibility to make code a little more messy, probably.
You still could ask our friend [pkuliyi2015](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) if he would consider about it.

Or, just comment that line by yourself, this will make it a work around.
