### ISSUE TITLE
Image problem

### ISSUE THREAD

**Issue by xbahenrytam** [Kahsolt/stable-diffusion-webui-vae-tile-infer#3]
When I enable "Yet Another VAE Tiling" with its default settings, the output image seems like covered by a gray mask.
I don't know how to describe so I upload a [**problem image**](https://imgur.com/a/cQBr8rh)
BTW, I also trying using "https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111", and if I enable Yet Another VAE Tiling, no matrer other extensions are using or not, the problem occured.

**Comment by Kahsolt** [comment]
Is pkuliyi2015's version work for you, with the same setting? 
This repo is now mainly for experiments and code study, we put updates on pkuliyi2015's repo there.

If you are doing img2img, using "GN_syn=Approx" in vae encoder will cause vital color shift, might be the reason for your case.
In pkuliyi2015's version, check "Fast Encoder Color Fix" should fix it.

**Comment by xbahenrytam** [comment]
THX I'll try later. pkuliyi2015's version is working normally; I'm still learning how to use this extension for better results.
It seems that Yet Another VAE Tiling is set to enable for default, so I produce some wrong images until I found it and disable it.

**Comment by Kahsolt** [comment]
Thanks for the report, and sorry for getting you confused 😂
I'll make it disabled by default
